### ISSUE TITLE
Same periodicity specified twice for a single torsion in smirnoff99Frosst-1.1.0.offxml

### ISSUE THREAD

**Issue by coleb** [openforcefield/smirnoff99Frosst#106]
smirnoff99Frosst-1.1.0.offxml has the following torsion with periodicity1="3" and periodicity3="3" both with phase 180 degrees, but different force constants, 0.38 and 1.0:
```         
<Proper smirks="[#1:1]-[#6X4:2]-[#6X3:3]=[#6X3:4]" periodicity1="3" periodicity2="1" periodicity3="3" phase1="180.0 * degree" phase2="0.0 * degree" phase3="180.0 * degree" k1="0.38 * mole**-1 * kilocalorie" k2="1.15 * mole**-1 * kilocalorie" k3="1.0 * mole**-1 * kilocalorie" id="t19" idivf1="1.0" idivf2="1.0" idivf3="1.0"></Proper>
```
Is this intentional to have the same periodicity twice? Is it permitted by the specification? Should I just add the force constants together? Or is this a bug? This is the only torsion with this, so has me curious. 

Thanks!

**Comment by davidlmobley** [comment]
@coleb That's certainly a bug, since this won't do anything other than add up to twice the force constant it should have.

@hyejang can you check this in the parsley release? Probably this means we are missing a term with a lower periodicity, e.g. "periodicity1=1", or... 

@cbayly13 do you know what the intention was here in `smirnoff99Frosst`? I may be able to do some archaeology to sort it out but it'll take me a while to get to it.

**Comment by davidlmobley** [comment]
This is a bug of a sort, but we think it's a "won't fix" bug for `smirnoff99frosst`; @hyejang dug up Chris's source materials and this basically appears there. We think the parent force fields had some disagreement as to the force constant here and that resulted in a small duplication. When I saw it I worried it meant we were missing a different term, but really it seems to just be a partial duplication. We could remove it, but it perhaps is not necessary since this is probably still roughly a faithful port.

Our Parsley force fields are what we're currently developing and we will remove the duplicate term from there (as they inherited it), which shouldn't affect outcomes but will make things cleaner.

I'll close for now, but reopen if you think more is needed here.

**Comment by coleb** [comment]
Just so I can be certain, as you said 'twice the force constant', k1=0.38 and k3=1.0, isn't twice. Is this the actual function? 

  U(phi) = (1.0 + 0.38) * (1 + cos(3 * phi - 180.0)) + (1.15) * (1 + cos(1 * phi - 0.0))

That is, the k3=1.0 isn't overriding the k1=0.38.

While I have your attention and this is just the kind of thing I should write a test case for, is there a list of molecule geometries (SDFs?) and energies for either smirnoff99Frosst or parsley? I'm also just a little confused about the distinction between Parsley (https://github.com/openforcefield/openforcefields), this this repo smirnoff99Frosst. 

Thanks!

**Comment by davidlmobley** [comment]
@coleb -- sorry, "twice the force constant" was actually not correct by any means. I would actually have to look at the guts to see what is being done here. EITHER we're getting the function you note, `U(phi) = (1.0 + 0.38) * (1 + cos(3 * phi - 180.0)) + (1.15) * (1 + cos(1 * phi - 0.0))`, OR `U(phi) = A * (1 + cos(3 * phi - 180.0)) + (1.15) * (1 + cos(1 * phi - 0.0))` where A is either 1.0 or 0.38, depending on which one was read first. I suspect it's the latter -- I don't think we implemented our spec expecting people to specify multiple force constants of the same periodicity, so it's probably the case that whatever is read last overrides what was read first. 

To answer your other questions: On *Parsley (OpenFF 1.0) vs smirnoff99Frosst*:
- `smirnoff99Frosst` (this repo) was/is a port of parm@frosst into the SMIRNOFF format. It will never be refit (since it is a **port**, not a refit), and any updates will just be minor fixes (and are probably unlikely at this point). 
- OpenFF 1.x, "Parsley", lives in https://github.com/openforcefield/openforcefields as will our other new force fields in this family as they come out. It is a full refit of `smirnoff99Frosst` based on new data, but is related in that it retains the same chemical perception (typing). The fitting process is described here: https://openforcefield.org/news/introducing-openforcefield-1.0/

So if you're after our latest and greatest/best force fields you should be using OpenFF-1.0.x and descendants, from `https://openforcefield.org/news/introducing-openforcefield-1.0/`. 

In terms of testing geometries and energetics, these are available some of our release packages. We're working on making this more transparent but for right now, if you want the Parsley (OpenFF 1.0) geometries/energies for testing, you can get them here: https://github.com/openforcefield/openforcefield-forcebalance/releases/tag/v1.0.0-RC1 (probably also linked in the blog post).

cc @j-wags
