### ISSUE TITLE
Conda installing on different channels

### ISSUE THREAD

**Issue by bannanc** [openforcefield/smirnoff99Frosst#50]
We have the force field on the mobleylab conda channel and most other things in the omnia channel. I think it would be better for everything for open-forcefield-group to be in the same channel, at least in the long run. Should we make an OFF channel? Or move everything into Omnia?

**Comment by jchodera** [comment]
Omnia for now. Later migrate to conda-forge following the omnia roadmap. Otherwise it will unnecessarily increase our maintenance burden, and my group does not have the capacity to handle that, so it would be all on the Mobley lab to support if we go any other way.

**Comment by davidlmobley** [comment]
We had to temporarily put this into the Mobleylab channel because of the lag in getting things into Omnia (Nathan needed something conda-installable for Orion in the crunch around CUP that worked immediately so we couldn't wait overnight). I'm fine with moving it into Omnia.

@jchodera - you refer to the omnia roadmap; where is this? And when is the migration to conda-forge happening? Somewhat relatedly, @nividic has been trying to get LOMAP working with Python 3 on Omnia but because of the huge number of out-of-date packages in the channel (I believe he mentioned RDKit among others) he's worrying he is going to have to put it in a different channel instead or make himself responsible for updating a wide variety of packages in Omnia, which he doesn't have time to do. What's the plan for dealing with maintenance of non-Omnia packages in the Omnia channel? I totally understand your group not wanting to take on unnecessary maintenance burden, but it's also (in cases like LOMAP) not clear how my group can avoid taking on unnecessary maintenance burden to get things INTO Omnia.

**Comment by jchodera** [comment]
> @jchodera - you refer to the omnia roadmap; where is this? 

Right now, it's just summarized in issues.

> And when is the migration to conda-forge happening? 

As soon as we have time to switch from putting out fires to updating the build system, we are finishing https://github.com/omnia-md/conda-recipes/pull/667 to switching to a CentOS 6 based build system and add the `conda-forge` channel as a prerequisite. At that point, package maintainers can start to migrate packages that don't depend on OpenMM over to `conda-forge` or use `conda-forge` packages as a dependency without it breaking everything.

We'll also work to migrate openmm to `conda-forge` once that happens, which will take a bit more work because of the more complex build environment.

> Somewhat relatedly, @nividic has been trying to get LOMAP working with Python 3 on Omnia but because of the huge number of out-of-date packages in the channel (I believe he mentioned RDKit among others) he's worrying he is going to have to put it in a different channel instead or make himself responsible for updating a wide variety of packages in Omnia, which he doesn't have time to do. What's the plan for dealing with maintenance of non-Omnia packages in the Omnia channel? I totally understand your group not wanting to take on unnecessary maintenance burden, but it's also (in cases like LOMAP) not clear how my group can avoid taking on unnecessary maintenance burden to get things INTO Omnia.

Which packages specifically do you need updated (besides `rdkit`)?

If you can go straight into `conda-forge`, that might be a better option if you don't need any `omnia` dependencies. But you'll have to dive in on your own.

**Comment by nividic** [comment]
Hi there, let me finish to updating Lomap to py3 and I'll let you asap with packages need to be updated. I'm still testing. I should finish during this weekend

**Comment by bannanc** [comment]
Ok, thanks! 

So long story short we should migrate smirnoff99Frosst to the omnia channel for now.

**Comment by nividic** [comment]
I checked the anaconda omnia repository and I think the only missing package should be pygraphviz version 1.4rc1 for python 3.4

**Comment by davidlmobley** [comment]
@nividic - so you're saying `pygraphviz` needs an update from 1.3 to 1.4rc1? Can you just do a PR to update the conda recipe?

**Comment by jchodera** [comment]
> I checked the anaconda omnia repository and I think the only missing package should be pygraphviz version 1.4rc1 for python 3.4 linux and OS X

@Lnaden is about to merge https://github.com/omnia-md/conda-recipes/pull/761 which will allow you to use `conda-forge` dependencies, so if you can find what you need there, you'll be able to use it without having to make any additional recipes for dependencies.

**Comment by nividic** [comment]
I cannot find the package on conda-forge. I'll try to build it in omnia

**Comment by jchodera** [comment]
I think you just have to [update this part of the omnia recipe](https://github.com/omnia-md/conda-recipes/blob/master/pygraphviz/meta.yaml#L5-L8) to the [latest pip version](https://pypi.python.org/pypi/pygraphviz/1.4rc1).

**Comment by davidlmobley** [comment]
Yes, @nividic - you should be able to just update the recipe.

**Comment by nividic** [comment]
I updated the recipe and I pulled a request on omnia yesterday night. I used I recipe that I download from anaconda. On my linux box I was able to build the latest version of pygraphviz by using it. I also uploaded it in my anaconda repository: https://anaconda.org/nividic

**Comment by davidlmobley** [comment]
Ah, this is the relevant PR: https://github.com/omnia-md/conda-recipes/pull/765

**Comment by bannanc** [comment]
I was checking another old issue when I saw this one, I think it can be closed right?

**Comment by j-wags** [comment]
Yes, thanks for the reminder. I think this can be closed, along with a few others.
