### ISSUE TITLE
Address poor behavior with ethers and amines with halogens

### ISSUE THREAD

**Issue by bannanc** [openforcefield/smirnoff99Frosst#71]
@davidlmobley noticed a problem when running gas phase MD for `'c1ccc(cc1)OC(C(F)F)F'`. Looking at MD simulations for substructures in that molecule, I've isolated the problem related to the ether with halogens substructure. 

In minimized structures everything looks fine, but after some MD steps we end up with structures like these:
This is the original tested molecule (light pink = fluorine):
<img src="https://user-images.githubusercontent.com/11968541/35645415-93b98422-0680-11e8-99ff-d6a687a0c201.png" width="400">

The same thing occurs for the ether fragment. 
<img src="https://user-images.githubusercontent.com/11968541/35645432-a3e644a2-0680-11e8-805a-1e9f3c10aae3.png" width="400">

The problem seems to occur for all halogens (here is iodine, I also checked Cl and Br)
<img src="https://user-images.githubusercontent.com/11968541/35645391-7c1f4f86-0680-11e8-9dd2-598e5ed1feb2.png" width="400">
(note - the purple atom is an iodine)

I think this may be similar to the issue we fixed with the ether torsions last spring. #14 
Here are the torsions for the ether bond currently in smirnoff99Frosst (in the smirnoffishFrcmod style):

```
[*:1]-[#6X4:2]-[#8X2H0:3]-[*:4]      3  1.15    0.0   3.0  parm99 X -CT-OS-X JCC,7,(1986),230
[#6X4:1]-[#6X4:2]-[#8X2H0:3]-[#6X4:4]      1  0.383    0.0  -3.0  parm99 CT-CT-OS-CT
[#6X4:1]-[#6X4:2]-[#8X2H0:3]-[#6X4:4]      1  0.100  180.0   2.0  parm99 CT-CT-OS-CT
[#6X4:1]-[#6X4:2]-[#8X2:3]-[#6X3:4]  1  0.383    0.0  -3.0  parm99 CT-CT-OS-C  Junmei et al, 1999
[#6X4:1]-[#6X4:2]-[#8X2:3]-[#6X3:4]  1  0.800  180.0   1.0  parm99 CT-CT-OS-C  Junmei et al, 1999
[#6X4:1]-[#8X2:2]-[#6X4:3]-[#8X2:4]  1  0.100    0.0  -3.0  parm99 CT-OS-CT-OS  Junmei et al, 1999
[#6X4:1]-[#8X2:2]-[#6X4:3]-[#8X2:4]  1  0.850  180.0   2.0  parm99 CT-OS-CT-OS  Junmei et al, 1999
[#6X4:1]-[#8X2:2]-[#6X4:3]-[#8X2:4]  1  1.350  180.0   1.0  parm99 CT-OS-CT-OS  Junmei et al, 1999
[#6X4:1]-[#8X2:2]-[#6X4:3]-[#7X3:4]  1  0.383    0.0  -3.0  parm99 CT-OS-CT-N*  parm98.dat, TC,PC,PAK
[#6X4:1]-[#8X2:2]-[#6X4:3]-[#7X3:4]  1  0.650    0.0   2.0  parm99 CT-OS-CT-N*  Piotr et al.
```

This catch all parameter:
```
[*:1]-[#6X4:2]-[#8X2H0:3]-[*:4]      3  1.15    0.0   3.0  parm99 X -CT-OS-X JCC,7,(1986),230
```
catches all the `[$halogen]-C-O-C` torsions.

**Comment by bannanc** [comment]
@cbayly13 it would be great to get your eyes on this when you have time. 
David found this while making stuff for his [solvation lecture](https://github.com/MobleyLab/drug-computing/blob/master/uci-pharmsci/lectures/solvation/solvation.ipynb). I copied just the gas phase code to a google doc and ran a few simulations here [on google drive](https://drive.google.com/drive/folders/1XJ71ne0MFR8HIiCyXdYu3dDEaB2toqpq?usp=sharing)

It generates a pdb file for each molecule with the trajectory in the corresponding `nc` file.

**Comment by bannanc** [comment]
The same thing seems to happen for halogens by amines (I ran that simulation yesterday and forgot to add the imagine)
![40377fb6-4b32-4419-b702-a6c2546f56e3](https://user-images.githubusercontent.com/11968541/35663265-39f8f502-06d1-11e8-950b-ffa4f30fcaac.png)

Per phone call with @cbayly13 earlier today, we do not think this is a torsion problem, but the angles look reasonable to me. Someone will need to dig a lot deeper at some point in the future, I will not have time for a least a few weeks. 

For the record incase someone else tries to dig into this:
Amines and ethers without any halogens perform normally. Also, halogenated thioethers seem to perform normally. 

Some things Chris suggested for investigation purposes on the phone today:
* Run a minimization starting from the bizzarre structures
* Run MD at a lower temperature
* Try the same compounds with GAFF in OpenMM to see if for some reason the issue is there
* Otherwise, try experimenting with bond, angle, or torsion parameters to see if changing any of them changes this behavior.

**Comment by davidlmobley** [comment]
I wonder if a simple thing to do to test would be to *add* a halogen to a minimal force field such as AlkEthOH, or port in halogen parameters from smirnoff99Frosst. It may be easier to see what it is that breaks halogens than to try to think through the whole force field.

**Comment by davidlmobley** [comment]
@bannanc @cbayly13 - I actually wondering if perhaps this is not a bug in the forcefield but a problem with visualization and the tools utilized. I don't have time to check right now (though maybe Caitlin can) but it seems like we'd see something very similar to this if the atoms were getting shuffled in the topology used for visualization (but the underlying simulation is fine).

After thinking of this possibility, I realized my code used here actually essentially uses two different Topologies -- `generateTopologyFromOEMol` (a sort of lame helper function internal to `openforcefield`) is used for running the simulations, and the `oeommtools` functionality `openmmTop_to_oemol` is used to create a final OEMol of what was simulated which is then written to a PDB file using `OEWriteMolecule` and THIS is read via `mdtraj` to generate a Topology which is used for visualization.

If I had to bet, I'd bet that our problem is that the two Topologies in question have different atom orders whenever there are halogens, so when we load the trajectory via `mdtraj` some of the atom orders are reshuffled and so the visualization looks completely wrong.

An easy way to check would just be to use mol2 or PDB input for everything and repeat the whole process, NEVER generating a topology via any of the ancillary functions (`generateTopologyFromOEMol` or `openmmTop_to_oemol`). 

It would also be easy to check by just being consistent and using either `generateTopologyFromOEMol` or `openmmTop_to_oemol` everywhere, but not both. 

Since the force field itself is fairly heavily tested (as is our format) a visualization problem seems much more plausible to me than a huge, dramatic problem with the force field. I also couldn't understand why simulations wouldn't be crashing if we were seeing such crazy geometries; again, a visualization problem would be more consistent.

**Comment by bannanc** [comment]
@davidlmobley you were right! This whole problem was caused my some kind of mis-ordering. All I did was make a pdb of the original molecule instead of converting the openMM system back to an oemol at the end and everything is fine. (I'll do a PR to your course github)

I'm closing this issue. 

(fyi @cbayly13)
